server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:file:./test
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true